spring.application.name=mybatis-sample-1

# DB接続設定 (pgAdmin4を使用)
spring.datasource.url=jdbc:postgresql://localhost:5432/テーブル名
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL初期化の設定 (schema.sql, data.sqlを起動時に実行する)
spring.sql.init.mode=always

# MyBatisの設定
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml

# ログレベルの設定
logging.level.com.example.demo.mapper=debug
